version: '3'
services:
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wos
        MYSQL_USER: devwos
        MYSQL_PASSWORD: test
 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
          PMA_HOST: db
    
    php:
        build: docker/php
        ports:
          - "9072:80"
          - "8000:8000"
        depends_on:
          - db
        volumes:
            - ./docker/vhosts:/etc/apache2/sites-enabled
            - .:/var/www/backend
   